### ISSUE TITLE
AccessTokenDelegatingHandler throws when creating without InnerHandler

### ISSUE THREAD

**Issue by damianh** [DuendeArchive/IdentityModel#119]
_here we go again; how did I miss this first time?_...

The `innerHandler` is an optional parameter whose default is null..

https://github.com/IdentityModel/IdentityModel2/blob/624d5247768e1779bc28ebb4bc5a4f9f944c823c/src/IdentityModel/Client/AccessTokenDelegatingHandler.cs#L77-L78

...  is passed through to this `DelegatingMessageHandler`...

https://github.com/dotnet/corefx/blob/dbea234b95c8ce39c6a1c0243433de0ea36f91af/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L42-L45

... which just blindly calls the property setter which will throw...

https://github.com/dotnet/corefx/blob/dbea234b95c8ce39c6a1c0243433de0ea36f91af/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L19-L30

IMHO `DelegatingHandler` should should check for null and ignore if so. But what are the chances of getting this updated?

PR inbound.

**Comment by damianh** [comment]
So the tests set the handler and dont cover scenario where innerHandler is null ffs.

**Comment by leastprivilege** [comment]
thanks!

**Comment by xperiandri** [comment]
Was this fix released?

**Comment by leastprivilege** [comment]
yes

**Comment by dudedev** [comment]
I am using IdentityModel v3.10.2. But it still throws "System.InvalidOperationException: The inner handler has not been assigned.".
Usage:                
```
 new AccessTokenDelegatingHandler(tokenEndpoint, clientId, clientSecret, scope);
```
Am I using the incorrect version?

**Comment by leastprivilege** [comment]
@damianh
